export const initialProducts = [
  {
    qty: 0,
    id: 1,
    name: "Laptop",
    price: 55000,
    stock: 10,
    category: "Electronics",
  },
  {
    qty: 0,
    id: 2,
    name: "Smartphone",
    price: 22000,
    stock: 15,
    category: "Electronics",
  },
  {
    qty: 0,
    id: 3,
    name: "Wireless Mouse",
    price: 850,
    stock: 25,
    category: "Accessories",
  },
  {
    qty: 0,
    id: 4,
    name: "Mechanical Keyboard",
    price: 3200,
    stock: 12,
    category: "Accessories",
  },
  {
    qty: 0,
    id: 5,
    name: "Bluetooth Speaker",
    price: 2800,
    stock: 18,
    category: "Electronics",
  },
  {
    qty: 0,
    id: 6,
    name: "Smart Watch",
    price: 4500,
    stock: 20,
    category: "Wearables",
  },
  {
    qty: 0,
    id: 7,
    name: "Headphones",
    price: 1800,
    stock: 30,
    category: "Audio",
  },
  {
    qty: 0,
    id: 8,
    name: "USB Pen Drive",
    price: 650,
    stock: 40,
    category: "Storage",
  },
  {
    qty: 0,
    id: 9,
    name: "External Hard Disk",
    price: 5200,
    stock: 8,
    category: "Storage",
  },
  {
    qty: 0,
    id: 10,
    name: "Gaming Monitor",
    price: 14500,
    stock: 6,
    category: "Electronics",
  },
  {
    qty: 0,
    id: 11,
    name: "Printer",
    price: 7600,
    stock: 9,
    category: "Office",
  },
  {
    qty: 0,
    id: 12,
    name: "WiFi Router",
    price: 2400,
    stock: 14,
    category: "Networking",
  },
  {
    qty: 0,
    id: 13,
    name: "Webcam",
    price: 1900,
    stock: 16,
    category: "Accessories",
  },
  {
    qty: 0,
    id: 14,
    name: "Power Bank",
    price: 1500,
    stock: 22,
    category: "Mobile Accessories",
  },
  {
    qty: 0,
    id: 15,
    name: "LED TV",
    price: 38000,
    stock: 5,
    category: "Electronics",
  },
];
